/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //Sidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  DocsSidebar: [
    {
      type: 'category',
      label: 'Project Information',
      collapsed: false,
      items: ['documentation/project/introduction', 'documentation/project/about', 'documentation/project/terms', 'documentation/project/community'],
    },
    {
      type: 'category',
      label: 'Panel',
      collapsed: false,
      items: ['documentation/panel/getting_started', 'documentation/panel/webserver_configuration', 'documentation/panel/additional_configuration', 'documentation/panel/updating', 'documentation/panel/troubleshooting', 'documentation/panel/legacy_upgrade'],
    },
    {
      type: 'category',
      label: 'Wings',
      collapsed: false,
      items: ['documentation/wings/installing', 'documentation/wings/upgrading', 'documentation/wings/migrating', 'documentation/wings/configuration']
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: ['documentation/tutorials/mysql_setup', 'documentation/tutorials/creating_ssl_certificates']
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: ['documentation/guides/mounts', 'documentation/guides/php_upgrade']
    }
  ],
  CommunitySidebar: [
    {
      type: 'category',
      label: 'Community Guides',
      link: {type: 'doc', id: 'community/community_guides/index'},
      collapsed: false,
      items: ['community/community_guides/about']
    },
    {
      type: 'category',
      label: 'Panel Installation',
      collapsed: false,
      items: ['community/installation-guides/panel/centos7', 'community/installation-guides/panel/centos8', 'community/installation-guides/panel/debian']
    },
    {
      type: 'category',
      label: 'Wings Installation',
      collapsed: false,
      items: ['community/installation-guides/wings/centos7', 'community/installation-guides/wings/centos8', 'community/installation-guides/wings/debian']
    },
    {
      type: 'category',
      label: 'Creating Eggs',
      collapsed: false,
      items: ['community/creating_eggs/creating_a_custom_egg', 'community/creating_eggs/creating_a_custom_image']
    },
    {
      type: 'category',
      label: 'Game Configuration',
      collapsed: false,
      items: ['community/game_configuration/minecraft']
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: ['community/tutorials/add_node', 'community/tutorials/artisan']
    },
    {
      type: 'category',
      label: 'Customization',
      collapsed: false,
      items: ['community/customization/panel', 'community/customization/wings']
    },
  ],
};


module.exports = sidebars;
