/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //Sidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  DocsSidebar: [
    {
      type: 'category',
      label: 'Project Information',
      collapsed: false,
      items: ['Documentation/Project Information/introduction', 'Documentation/Project Information/about', 'Documentation/Project Information/terms', 'Documentation/Project Information/community'],
    },
    {
      type: 'category',
      label: 'Panel',
      collapsed: false,
      items: ['Documentation/Panel/getting_started', 'Documentation/Panel/webserver_configuration', 'Documentation/Panel/additional_configuration', 'Documentation/Panel/updating', 'Documentation/Panel/troubleshooting', 'Documentation/Panel/legacy_upgrade'],
    },
    {
      type: 'category',
      label: 'Wings',
      collapsed: false,
      items: ['Documentation/Wings/installing', 'Documentation/Wings/upgrading', 'Documentation/Wings/migrating', 'Documentation/Wings/configuration']
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: ['Documentation/Tutorials/mysql_setup', 'Documentation/Tutorials/creating_ssl_certificates']
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: ['Documentation/Guides/mounts', 'Documentation/Guides/php_upgrade']
    }
  ],
  CommunitySidebar: [
    {
      type: 'category',
      label: 'Community Guides',
      collapsed: false,
      items: ['Community/Community Guides/about']
    },
    {
      type: 'category',
      label: 'Panel Installation',
      collapsed: false,
      items: ['Community/Panel Installation/centos7', 'Community/Panel Installation/centos8', 'Community/Panel Installation/debian10', 'Community/Panel Installation/debian11']
    },
    {
      type: 'category',
      label: 'Wings Installation',
      collapsed: false,
      items: ['Community/Wings Installation/centos7', 'Community/Wings Installation/centos8', 'Community/Wings Installation/debian10', 'Community/Wings Installation/debian11']
    },
    {
      type: 'category',
      label: 'Creating Eggs',
      collapsed: false,
      items: ['Community/Creating Eggs/creating_a_custom_egg', 'Community/Creating Eggs/creating_a_custom_image']
    },
    {
      type: 'category',
      label: 'Game Configuration',
      collapsed: false,
      items: ['Community/Game Configuration/minecraft']
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: ['Community/Tutorials/add_node', 'Community/Tutorials/artisan']
    },
    {
      type: 'category',
      label: 'Customization',
      collapsed: false,
      items: ['Community/Customization/panel', 'Community/Customization/wings']
    },
  ],
};


module.exports = sidebars;
